# Generated by Django 5.2.7 on 2026-10-04 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="dashboard_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can sign in and view this company's cards.",
                related_name="companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
