# Generated by Django 5.2.7 on 2026-10-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_company_dashboard_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="industry",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="company",
            name="user_limit",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
