# Generated by Django 5.2.7 on 2026-10-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_company_industry_company_user_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="primary_color",
            field=models.CharField(default="#000000", max_length=7),
        ),
    ]
