# Generated by Django 5.2.7 on 2026-10-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_alter_company_primary_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="slogan",
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
